const tracks=[
{id:1,name:'Lead Vocal',type:'vocal',color:'#ff7168',icon:'◉',gain:.75,pan:0,clips:[['Verse 1',120,210],['Chorus',390,275],['Verse 2',720,230]]},
{id:2,name:'Harmony',type:'vocal',color:'#bc6ee8',icon:'◎',gain:.55,pan:-.2,clips:[['Harmony',410,240],['Harmony',960,180]]},
{id:3,name:'Drums',type:'audio',color:'#5ec8d8',icon:'♩',gain:.65,pan:0,clips:[['Anime Rock Kit',0,350],['Chorus Drums',360,320],['Verse Groove',690,290]]},
{id:4,name:'Bass',type:'instrument',color:'#6e8fec',icon:'≈',gain:.62,pan:0,clips:[['Bassline',110,230],['Bassline',380,290],['Bassline',710,260]]},
{id:5,name:'Electric Guitar',type:'instrument',color:'#e39b54',icon:'⌁',gain:.58,pan:.25,clips:[['Clean Arp',105,240],['Power Chords',370,305],['Clean Arp',700,260]]},
{id:6,name:'Strings',type:'instrument',color:'#dd6d9b',icon:'≋',gain:.48,pan:-.25,clips:[['Sustain',210,130],['Epic Strings',390,280],['Final Rise',930,220]]}
];
let selectedTrack=1,playing=false,currentSec=72,bpm=128,zoom=1,audioCtx,masterGain,timer,history=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderTracks(){
 $('#trackHeaders').innerHTML=tracks.map(t=>`<div class="track-head" data-id="${t.id}" style="--track-color:${t.color}"><span class="track-icon">${t.icon}</span><span class="track-label"><b>${t.name}</b><small>${t.type.toUpperCase()}</small></span><button class="mute">M</button><button class="solo">S</button><input class="track-volume" type="range" min="0" max="100" value="${t.gain*100}"></div>`).join('');
 $('#trackLanes').innerHTML=tracks.map(t=>`<div class="track-lane" data-id="${t.id}">${t.clips.map((c,i)=>`<div class="clip ${t.type==='instrument'?'midi':''}" data-index="${i}" style="left:${c[1]}px;width:${c[2]}px;--clip:${t.color}"><b>${c[0]}</b><i class="wave"></i></div>`).join('')}</div>`).join('');
 bindTracks(); scaleTimeline();
}
function bindTracks(){
 $$('.track-head').forEach(h=>h.addEventListener('click',e=>{selectedTrack=+h.dataset.id;const t=tracks.find(x=>x.id===selectedTrack);$('#inspectName').value=t.name;$$('.track-head').forEach(x=>x.style.background='');h.style.background='#1a1b22';e.stopPropagation()}));
 $$('.mute,.solo').forEach(b=>b.addEventListener('click',e=>{b.classList.toggle('on');e.stopPropagation();showToast(b.classList.contains('on')?(b.classList.contains('mute')?'트랙을 음소거했습니다':'트랙을 솔로로 재생합니다'):'트랙 설정을 해제했습니다')}));
 $$('.track-volume').forEach(r=>r.addEventListener('input',e=>{tracks.find(x=>x.id===+r.parentElement.dataset.id).gain=+r.value/100;e.stopPropagation()}));
 $$('.clip').forEach(c=>{c.addEventListener('click',e=>{$$('.clip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');e.stopPropagation()});makeDraggable(c)});
}
function makeDraggable(el){let startX,startLeft;el.addEventListener('pointerdown',e=>{startX=e.clientX;startLeft=parseFloat(el.style.left);el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(startX==null)return;let left=Math.max(0,startLeft+(e.clientX-startX)/zoom);if($('#snapBtn').classList.contains('active'))left=Math.round(left/30)*30;el.style.left=left+'px'});el.addEventListener('pointerup',()=>{if(startX!=null){const lane=el.parentElement,t=tracks.find(x=>x.id===+lane.dataset.id);t.clips[+el.dataset.index][1]=parseFloat(el.style.left);history.push('clip');showToast('클립 위치를 변경했습니다')}startX=null})}
function scaleTimeline(){const width=1200*zoom;$$('.track-lane,.ruler').forEach(x=>x.style.width=width+'px');$$('.ruler span').forEach(x=>x.style.width=120*zoom+'px');$$('.clip').forEach(c=>c.style.transform=`scaleX(${zoom})`)}
function buildRuler(){$('#ruler').innerHTML=Array.from({length:10},(_,i)=>`<span>${i*4+1}</span>`).join('')}
function formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60),ms=Math.floor(s%1*1000);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
function updatePlayhead(){const px=currentSec*(bpm/60)*30/4;$('#playhead').style.left=(px*zoom)+'px';$('#timeDisplay').textContent=formatTime(currentSec)}
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=.18;masterGain.connect(audioCtx.destination)}
function note(freq,start,duration,type='sine',volume=.1){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(volume,start+.02);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(masterGain);o.start(start);o.stop(start+duration)}
function scheduleBar(){if(!playing)return;initAudio();const now=audioCtx.currentTime+.02,beat=60/bpm;[220,261.63,329.63,293.66].forEach((f,i)=>{note(f,now+i*beat,beat*.85,i%2?'triangle':'sine',.07);note(f/2,now+i*beat,beat*.9,'square',.025)});for(let i=0;i<8;i++)note(i%2?100:70,now+i*beat/2,.04,'square',.025)}
function play(){initAudio();audioCtx.resume();playing=true;$('#playBtn').textContent='Ⅱ';scheduleBar();timer=setInterval(()=>{currentSec+=.05;updatePlayhead();if(Math.floor(currentSec*10)%(Math.round((60/bpm*4)*10))===0)scheduleBar()},50)}
function stop(reset=false){playing=false;clearInterval(timer);$('#playBtn').textContent='▶';if(reset){currentSec=0;updatePlayhead()}}
function showToast(text='변경사항을 적용했습니다'){const t=$('#toast');t.querySelector('strong').textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function addTrack(type){const map={vocal:['New Vocal','◉','#ff7168'],instrument:['New Instrument','♬','#7c91ef'],audio:['New Audio','〽','#5bc6cc'],video:['Video Scene','▣','#df6b9f']},v=map[type];tracks.push({id:Date.now(),name:v[0],type,color:v[2],icon:v[1],gain:.6,pan:0,clips:[]});renderTracks();$('#trackModal').hidden=true;showToast(`${v[0]} 트랙을 추가했습니다`)}
function aiAction(text){const user=document.createElement('div');user.className='msg user';user.innerHTML=`<p>${text}</p>`;$('#chat').append(user);setTimeout(()=>{let response='요청을 분석해 프로젝트에 적용했어요.';if(/후렴|웅장|드럼/.test(text)){const d=tracks.find(t=>t.name==='Drums');d.clips.push(['AI Power Drums',930,220]);response='마지막 후렴에 파워 드럼과 크래시를 추가하고 에너지를 높였어요.'}else if(/화음|하모니/.test(text)){tracks.find(t=>t.name==='Harmony').clips.push(['AI Harmony',720,210]);response='선택 구간에 3도 위 화음을 추가했어요.'}else if(/키|반키/.test(text)){response='마지막 후렴을 반키 올리고 보컬 전환음을 자연스럽게 연결했어요.'}renderTracks();const ai=document.createElement('div');ai.className='msg ai';ai.innerHTML=`<i>✦</i><p>${response}</p>`;$('#chat').append(ai);$('#chat').scrollTop=9999;showToast('AI Producer가 프로젝트를 수정했습니다')},650)}
function setup(){buildRuler();renderTracks();updatePlayhead();for(let i=0;i<13;i++){const n=document.createElement('i');n.className='note';n.style.cssText=`left:${35+i*48}px;top:${20+(i%5)*18}px;width:${28+(i%3)*12}px`;$('#pianoNotes').append(n)}}
$('#playBtn').onclick=()=>playing?stop():play();$('#stopBtn').onclick=()=>stop(true);$('#rewindBtn').onclick=()=>{currentSec=Math.max(0,currentSec-4);updatePlayhead()};$('#metroBtn').onclick=e=>e.currentTarget.classList.toggle('active');
$('#zoom').oninput=e=>{zoom=+e.target.value/100;scaleTimeline()};$('#zoomIn').onclick=()=>{$('#zoom').value=Math.min(170,+$('#zoom').value+10);$('#zoom').oninput({target:$('#zoom')})};$('#zoomOut').onclick=()=>{$('#zoom').value=Math.max(70,+$('#zoom').value-10);$('#zoom').oninput({target:$('#zoom')})};$('#snapBtn').onclick=e=>e.currentTarget.classList.toggle('active');
$$('.editor-tabs [data-editor]').forEach(b=>b.onclick=()=>{$$('.editor-tabs button,.editor-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`[data-panel="${b.dataset.editor}"]`).classList.add('active')});
$$('.inspector-tabs button').forEach(b=>b.onclick=()=>{$$('.inspector-tabs button,.side-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`[data-side-panel="${b.dataset.side}"]`).classList.add('active')});
$$('.toolnav [data-view]').forEach(b=>b.onclick=()=>{$$('.toolnav [data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const names={music:['Music Studio','ARRANGEMENT'],voice:['Voice Studio','SINGING & TRAINING'],character:['Character Studio','IDENTITY & ASSETS'],video:['Video Studio','STORYBOARD & MOTION'],library:['My Library','VOICES · CHARACTERS · STYLES']};$('#viewTitle').textContent=names[b.dataset.view][0];$('#viewSub').textContent=names[b.dataset.view][1];if(b.dataset.view==='video'){$('[data-editor="storyboard"]').click()}showToast(`${names[b.dataset.view][0]}로 전환했습니다`)});
$('#addTrackBtn').onclick=()=>$('#trackModal').hidden=false;$('.modal-close').onclick=()=>$('#trackModal').hidden=true;$$('.track-types button').forEach(b=>b.onclick=()=>addTrack(b.dataset.type));
$('#sendBtn').onclick=()=>{const v=$('#aiPrompt').value.trim();if(v){aiAction(v);$('#aiPrompt').value=''}};$('#aiPrompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#sendBtn').click()}};$$('.suggestion-action').forEach(b=>b.onclick=()=>aiAction(b.dataset.action==='drums'?'후렴의 드럼을 더 강하게 만들어줘':'후렴에 화음을 추가해줘'));$('.dismiss').onclick=()=>$('.suggestion').remove();
$('#rewriteBtn').onclick=()=>{const s=$('.lyrics-lines .selected span');s.textContent='기억의 저편에서 네 목소리가 와';showToast('AI가 선택 가사를 다시 썼습니다')};
$('#masterVolume').oninput=e=>{if(masterGain)masterGain.gain.value=+e.target.value/400;$('#masterDb').textContent=(-18+(+e.target.value/100)*15).toFixed(1)+' dB'};
$('#renderBtn').onclick=()=>{let n=0;const b=$('#renderBtn'),iv=setInterval(()=>{n+=10;b.textContent=`RENDER ${n}%`;if(n===100){clearInterval(iv);b.textContent='✓ COMPLETE';showToast('음악과 뮤직비디오 렌더가 완료되었습니다');setTimeout(()=>b.textContent='✦ RENDER',1800)}},160)};$('#exportBtn').onclick=()=>showToast('WAV · MP4 내보내기 창을 준비했습니다');$('#undoBtn').onclick=()=>showToast(history.length?'마지막 변경을 취소했습니다':'취소할 변경사항이 없습니다');
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['TEXTAREA','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();$('#playBtn').click()}if((e.ctrlKey||e.metaKey)&&e.key==='z'){$('#undoBtn').click()}});setup();
